### ISSUE TITLE
The whole server lag/glitches when player change the skin

### ISSUE THREAD

**Issue by tydaytygx** [safra36/PlayerSkin#13]
I thought it's the network problem the first time my server glitches, but I test for several times.
Just after the button players press to change the skins, the whole server lost for 0.5 second.
Is there any solution?

**Comment by safra36** [comment]
I don't think that's plugin related since i don't use any unseal methods, do you have any more info that could point me to the problem?

**Comment by tydaytygx** [comment]
> 
> 
> I don't think that's plugin related since i don't use any unseal methods, do you have any more info that could point me to the problem?

OK, I would test it and output the logs later, thx :)

**Comment by tydaytygx** [comment]
```
L 11/03/2020 - 19:42:32: World triggered "Round_End"
RecordSteamInterfaceCreation (PID 4572): SteamGameStats001 / 
RecordSteamInterfaceCreation (PID 4572): SteamGameStats001 / 
RecordSteamInterfaceCreation (PID 4572): SteamGameStats001 / 
RecordSteamInterfaceCreation (PID 4572): SteamGameStats001 / 
RecordSteamInterfaceCreation (PID 4572): SteamGameStats001 / 
L 11/03/2020 - 19:42:33: Starting Freeze period
L 11/03/2020 - 19:42:33: [SM] Exception reported: Language phrase "NoSkinHasBeenSet" not found (arg 5)
L 11/03/2020 - 19:42:33: [SM] Blaming: PlayerSkin.smx
L 11/03/2020 - 19:42:33: [SM] Call stack trace:
L 11/03/2020 - 19:42:33: [SM]   [0] PrintToChat
L 11/03/2020 - 19:42:33: [SM]   [1] Line 192, F:\_MyFiles\Sourcemod\Files\Working On\Project\PlayerSkins\PlayerSkin\scripting\PlayerSkin.sp::PlayerSpawn
L 11/03/2020 - 19:42:33: [SM] Exception reported: Language phrase "NoSkinHasBeenSet" not found (arg 5)
L 11/03/2020 - 19:42:33: [SM] Blaming: PlayerSkin.smx
L 11/03/2020 - 19:42:33: [SM] Call stack trace:
L 11/03/2020 - 19:42:33: [SM]   [0] PrintToChat
L 11/03/2020 - 19:42:33: [SM]   [1] Line 192, F:\_MyFiles\Sourcemod\Files\Working On\Project\PlayerSkins\PlayerSkin\scripting\PlayerSkin.sp::PlayerSpawn
[PlayerSkin] Gloves detected, skipping setting arms ..
```

```
L 11/03/2020 - 19:44:30: World triggered "Round_End"
RecordSteamInterfaceCreation (PID 4572): SteamGameStats001 / 
RecordSteamInterfaceCreation (PID 4572): SteamGameStats001 / 
RecordSteamInterfaceCreation (PID 4572): SteamGameStats001 / 
L 11/03/2020 - 19:44:31: Starting Freeze period
L 11/03/2020 - 19:44:31: [SM] Exception reported: Language phrase "NoSkinHasBeenSet" not found (arg 5)
```

@safra36 Hi safra36, I notice these two errors, and I found some players could not change the skins normally.
```
user already in database
```
some of them showed error model after choosing the default skin )


Thanks for your reply :)

**Comment by tydaytygx** [comment]
Is the skin-change timemer removed? Where could I set the timer of this new version?

**Comment by safra36** [comment]
@tydaytygx hi, thanks for the info, which translation file are you using? are you using the english one?

**Comment by tydaytygx** [comment]
> 
> 
> @tydaytygx hi, thanks for the info, which translation file are you using? are you using the english one?

@safra36 Thanks for your reply! Some players translation file is chi, me is en.
Seems the change-laggy  is still.
I re-push your new version to my server, I would test it later. Thanks.

**Comment by tydaytygx** [comment]
```
L 11/04/2020 - 00:33:49: [SM] Exception reported: Array index out-of-bounds (index -1, limit 66)
L 11/04/2020 - 00:33:49: [SM] Blaming: multi1v1.smx
L 11/04/2020 - 00:33:49: [SM] Call stack trace:
L 11/04/2020 - 00:33:49: [SM]   [1] Line 864, ./scripting/multi1v1.sp::Event_OnPlayerDeath
L 11/04/2020 - 00:33:49: World triggered "SFUI_Notice_Round_Draw" (CT "12") (T "0")
```

**Comment by safra36** [comment]
I don't think the issue is related to this plugin, your log refers to another plugin

**Comment by safra36** [comment]
since there is no info for this issue or any related manners, this issue will be closed.
