### ISSUE TITLE
sm_round_timeout 0.0 not take effect to disable the timeout

### ISSUE THREAD

**Issue by tydaytygx** [safra36/PlayerSkin#14]
```
csgo/addons/sourcemod/configs/config.playerskin.cfg
```
Everytime I start the server, this config file was set to the default.
For example, I set sm_round_timeout 0.0, but it would be overrided after the server starts
So I can not change the skin in the server only I manually set it after server starts and type ```sm plugins reload```
Is there any config file that I miss ( not the one could be overrided) ?

**Comment by safra36** [comment]
your config path seems to be incorrect, the correct path for this cfg should be `csgo\cfg\sourcemod\configs.playerskin.cfg`

**Comment by tydaytygx** [comment]
> 
> 
> your config path seems to be incorrect, the correct path for this cfg should be `csgo\cfg\sourcemod\configs.playerskin.cfg`
Sorry.
It's my mistake.
Yes, the config file is ```csgo\cfg\sourcemod\configs.playerskin.cfg```

```
// Enable/Disable categories support
// -
// Default: "0"
sm_cat_enable "0"

// Hide menu options if the guy does not have access to the skin.
// -
// Default: "0"
sm_hide_options "0"

// Hide menu options for opposite team
// -
// Default: "0"
sm_hide_teams "1"

// Enable/Disable per map skin system
// -
// Default: "1"
sm_mapskins_enable "1"

// Enable/Disable Command pskin
// -
// Default: "1"
sm_pskin_enable "1"

// Set this to add a timeout for users to be able to use skins before that time.
// -
// Default: "20.0"
sm_round_timeout "0.0"

// If true, will show skin menu to all users.
// -
// Default: "0"
sm_start_menu "0"

```

The server hint
```
[PlayerSkin] You can now use skins for 0.000000 seconds.
[PlayerSkin] Skins are now disabled.
```

Did I edit  it incorrectly?

**Comment by safra36** [comment]
`sm_round_timeout` is set to 0.0 here, the behavior is expected, maybe you changed the commented `Default` text to 20.0?

**Comment by tydaytygx** [comment]
@safra36 
Wait a second, the  commented ```// Default: 20.0``` would take effect? ( Or I misunderstood your reply?)
Now is 
```
// Set this to add a timeout for users to be able to use skins before that time.
// -
// Default: 20.0
sm_round_timeout 0.0

```
All text format.
But still 
```
[PlayerSkin] You can now use skins for 0.000000 seconds.
[PlayerSkin] Skins are now disabled.
```

**Comment by safra36** [comment]
you should change `sm_round_timeout 0.0` to `sm_round_timeout 20.0` not `// Default: 20.0` that's a comment and will not be executed

**Comment by tydaytygx** [comment]
> 
> 
> you should change `sm_round_timeout 0.0` to `sm_round_timeout 20.0` not `// Default: 20.0` that's a comment and will not be executed

Okay, I misunderstood.
I change 
```sm_round_timeout 0.0 ``` 
to  
```sm_round_timeout 100```

```
[PlayerSkin] You can now use skins for 100.000000 seconds.
```
Works fine, if I want to disable the timeout, how can I do?
Setting it to ```sm_round_timeout 0.0``` seems just set it to 0 second for players

**Comment by safra36** [comment]
you want that text to go away right?

**Comment by tydaytygx** [comment]
> 
> 
> > you want that text to go away right?

I mean disabling that timer function I just need to  set it ```sm_round_timeout 0```in the plugin previous verions 
But this version I set to ```sm_round_timeout 0``` is not disabling, just set it to 0.0 second, meaning no one could use it anymore?
By the way, don't let that hint text go away, that is useful XD
I just want to know the real meaning of  ```sm_round_timeout 0.0``` function
Meaning disable it or just set to 0.0 second?
I saw your readme calling it ```disable```
So I am very confused
Sorry for my bad operation of server-side.

**Comment by safra36** [comment]
yes, it will be set to disabled immediately, but this is a bug since the text should not be appear if the timer is set to 0 and they should be able to change their skins when every they want , there will be an update to fix that soon

**Comment by tydaytygx** [comment]
> 
> 
> > you want that text to go away right?
> > I mean disabling that timer function I just need to  set it `sm_round_timeout 0`in the plugin previous verions
> > But this version I set to `sm_round_timeout 0` is not disabling, just set it to 0.0 second, meaning no one could use it anymore?
> > By the way, don't let that hint text go away, that is useful XD
> > I just want to know the real meaning of  `sm_round_timeout 0.0` function
> > Meaning disable it or just set to 0.0 second?
> > I saw your readme calling it `disable`
> > So I am very confused
> > Sorry for my bad operation of server-side.



> 
> 
> you want that text to go away right?



> > > you want that text to go away right?
> 
> I mean disabling that timer function I just need to set it `sm_round_timeout 0`in the plugin previous verions
> But this version I set to `sm_round_timeout 0` is not disabling, just set it to 0.0 second, meaning no one could use it anymore?
> By the way, don't let that hint text go away, that is useful XD
> I just want to know the real meaning of `sm_round_timeout 0.0` function
> Meaning disable it or just set to 0.0 second?
> I saw your readme calling it `disable`
> So I am very confused
> Sorry for my bad operation of server-side.



> 
> 
> you want that text to go away right?



> 
> 
> yes, it will be set to disabled immediately, but this is a bug since the text should not be appear if the timer is set to 0 and they should be able to change their skins when every they want

@safra36 Thanks for your apply.I would keep testing for more info.
