### ISSUE TITLE
[Bug] Skins not re-applying.

### ISSUE THREAD

**Issue by stunslave** [safra36/PlayerSkin#3]
**Skins not re-applying to players on new round start / suicide / map reload / map change or server restart. Players have to re-select their models.**

I'm using mysql and the latest version of the PlayerSkins plugin.

-----------------------------------------------------------------

**Errors:** _No other errors than the ones below._

L 09/03/2019 - 13:50:30: [SM] Exception reported: Current result set has no fetched rows
L 09/03/2019 - 13:50:30: [SM] Blaming: PlayerSkin.smx
L 09/03/2019 - 13:50:30: [SM] Call stack trace:
L 09/03/2019 - 13:50:30: [SM]   [0] SQL_FetchString
L 09/03/2019 - 13:50:30: [SM]   [1] Line 1438, D:\10_Servers\Fun and Games\csgo\addons\sourcemod\scripting\PlayerSkin.sp::IsUserWithSkins
L 09/03/2019 - 13:50:30: [SM]   [2] Line 162, D:\10_Servers\Fun and Games\csgo\addons\sourcemod\scripting\PlayerSkin.sp::PlayerSpawn

L 09/03/2019 - 13:50:30: [SM] Exception reported: Handle 6f00524 is invalid (error 1)
L 09/03/2019 - 13:50:30: [SM] Blaming: PlayerSkin.smx
L 09/03/2019 - 13:50:30: [SM] Call stack trace:
L 09/03/2019 - 13:50:30: [SM]   [0] CloseHandle
L 09/03/2019 - 13:50:30: [SM]   [1] Line 105, D:\10_Servers\Fun and Games\csgo\addons\sourcemod\scripting\PlayerSkin.sp::RoundStart 

-----------------------------------------------------------------

**Other than the above everything works 100's!**

**Comment by o1f** [comment]
Me too..

![image](https://user-images.githubusercontent.com/28326356/86560099-2b3f8380-bf90-11ea-9aeb-184687b8bf9f.png)

**Comment by safra36** [comment]
closing this issue since there has been no other reports or observations regarding this issue
