### ISSUE TITLE
[BUG] KillTimer - RoundStart

### ISSUE THREAD

**Issue by crashzk** [safra36/PlayerSkin#5]
The plugin works normally, I was able to choose my skins and everything, but I've been getting a flood of errors in the server log:
```
L 02/01/2020 - 18:00:17: [SM] Exception reported: Invalid timer handle 19a50a10 (error 1)
L 02/01/2020 - 18:00:17: [SM] Blaming: PlayerSkin.smx
L 02/01/2020 - 18:00:17: [SM] Call stack trace:
L 02/01/2020 - 18:00:17: [SM]   [0] KillTimer
L 02/01/2020 - 18:00:17: [SM]   [1] Line 105, E:\_MyFiles\Sourcemod\Files\Working On\Project\PlayerSkins\PlayerSkin\scripting\PlayerSkin.sp::RoundStart
```
[errors_20200201.log](https://github.com/safra36/PlayerSkin/files/4143244/errors_20200201.log)

I am using the following version of the plugin:

> "PlayerSkin" (5.0.2 (Build 16)) by noBrain

**Comment by safra36** [comment]
I'm aware of this issue but haven't found a fix for it yet, my testings has been useless till now ..

**Comment by crashzk** [comment]
> I'm aware of this issue but haven't found a fix for it yet, my testings has been useless till now ..

I understand, I will be testing this new version that you made available, I will be seeing if the error continues.

In any case, thank you for now!

**Comment by safra36** [comment]
Fixed
