### ISSUE TITLE
[Feature Request] Apply skin on both teams automatically

### ISSUE THREAD

**Issue by crashzk** [safra36/PlayerSkin#7]
Currently the config `skin.ini` works like this:
```
"EXAMPLE_SKIN"
    {
        "Name" "NAME TO DISPLAY IN MENU"
        "Skin" "MODEL PATH"
        "Arms" "ARMS MODEL PATH"
        "Team" "TEAM WHICH THE SKIN IS FOR"
        "Flag" "SOURCEMOD ADMIN FLAGS (LIKE Z FOR ADMIN ROOT)"
        "u_id" "SKIN UNIQUE ID (this must be unique per skin)"
        "catgroup" "cat_ID"
    }
```
If I leave the option **"Team"** in the open, skins can be used by both teams, CT and TR.

It would be interesting if in this case, that is, you do not have a team configured, when the player chooses the skin it automatically applies to both teams.

# WHY THIS CHANGE
I realized that if there is no Team configured on the skin, I have to choose the skin again on the other side of the team, that is, I choose it from CT and when I change teams, I have to choose again.

It would be possible in future upgrades @safra36?

**Comment by safra36** [comment]
Yeap it's possible but if will replace their skin on ther otherside if they already have a skin, what about that one?

**Comment by crashzk** [comment]
> Yeap it's possible but if will replace their skin on ther otherside if they already have a skin, what about that one?

Good question, I believe it would be interesting to leave the skins that he is in if he already has a side chosen, that is, if he already has a TR skin, but choose a skin while he is in CT, if that skin can be applied in both teams , will only put it on TR if it doesn't have a skin already selected, even the other way around.

**Comment by safra36** [comment]
This feature was added to the plugin and was tested with several skins, feel free to report back any bugs
